### 
GET http://localhost:5000

### 


POST http://localhost:5000/api/register 
Content-Type: application/json 

{ "name": "Gedas", "email": "Gedas@email.com", "password": "123456" }

### POST 
POST http://localhost:5000/api/login 
Content-Type: application/json

{ "email": "Gedas11@email.com", "password": "1234567" }

### GET 
GET http://localhost:5000/api/questions

### POST 
POST http://localhost:5000/api/questions
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkzNDUxNjQsImV4cCI6MTY1OTM0ODc2NH0.1gEXtSB32H8pFkQTddV-68rFIrqBMpaNLqxMdxXHFEU

{ "title": "Questionnn", "content": "Question" }

### PATCH 
PATCH http://localhost:5000/api/questions/3
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE

{ "title": "New answer", "content": "New Answer 222" }

### DELETE 
DELETE http://localhost:5000/api/questions/17 
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE

### GET 
GET http://localhost:5000/api/questions/1/answers 
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE

### POST 
POST http://localhost:5000/api/questions/1/answers 
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE

{ "content": "ABDDDD" }

### PATCH 
PATCH http://localhost:5000/api/answers/2 
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE

{ "content":"updated 003" }

### DELETE 
DELETE http://localhost:5000/api/answers/2 
Content-Type: application/json 

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkyODAyNTUsImV4cCI6MTY1OTI4Mzg1NX0.2FG6sDK0eexNige9BHQ3cPwCIf9E36fTmG_XFfJSeqE